### ISSUE TITLE
User should be warned if DYALOGLINK points to an unreadable folder

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/qSE#1]
At startup, the user needs to be warned if the most important parts of initialisation cannot be performed due to invalid configuration.

Andy needs to be consulted about exactly how the warning should be issued, whether APL should terminate, etc.

**Comment by abrudz** [comment]
After consulting Andy, now prints `Cannot read DYALOGLINK ("path/given"). Press Enter.'` then pauses for 5 seconds and quits with code 1 (initialisation error).
